# Generated by Django 2.1 on 2019-09-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_requested_by', models.CharField(max_length=30)),
                ('order_discount_percent', models.FloatField(blank=True, null=True)),
                ('order_total_amount', models.FloatField()),
                ('order_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_product_quantity', models.IntegerField()),
                ('orderdetails_total_amount', models.FloatField()),
                ('order_prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryapp.ProductMaster')),
            ],
            options={
                'db_table': 'order_details',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_orderdetails',
            field=models.ManyToManyField(to='orderapp.OrderDetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryapp.VendorDetails'),
        ),
    ]
