# Generated by Django 2.1 on 2019-09-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=45)),
                ('cust_dob', models.DateField()),
                ('cust_mob', models.CharField(max_length=13)),
                ('cust_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cust_addr', models.TextField(max_length=45)),
                ('cust_pin', models.CharField(max_length=6)),
                ('cust_created_date', models.DateTimeField(auto_now_add=True)),
                ('cust_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.City')),
            ],
            options={
                'db_table': 'customer_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('cust_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_type_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_id', models.AutoField(primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'district',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=45)),
                ('state_initials', models.CharField(max_length=45)),
                ('state_code', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'state',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='dist_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.State'),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='cust_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.CustomerType'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.District'),
        ),
    ]
