# Generated by Django 2.1 on 2019-09-29 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicleapp', '0001_initial'),
        ('inventoryapp', '0001_initial'),
        ('taxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourCategory',
            fields=[
                ('lab_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_cat_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'labour_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LabourDetails',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=45)),
                ('lab_mob_no', models.CharField(max_length=13)),
                ('lab_addr', models.TextField()),
                ('lab_city', models.CharField(max_length=30)),
                ('lab_pin', models.IntegerField()),
                ('lab_cat', models.ManyToManyField(to='servicesapp.LabourCategory')),
            ],
            options={
                'db_table': 'labour_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LabourOperationMaster',
            fields=[
                ('lab_op_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_op_code', models.CharField(max_length=20)),
                ('lab_op_name', models.CharField(max_length=45)),
                ('lab_op_description', models.TextField()),
                ('lab_op_work_hrs', models.FloatField(blank=True, null=True)),
                ('lab_op_rate', models.FloatField(blank=True, null=True)),
                ('lab_op_charges', models.FloatField(blank=True, null=True)),
                ('lab_tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxapp.TaxMaster')),
                ('labop_labcat', models.ManyToManyField(to='servicesapp.LabourCategory')),
            ],
            options={
                'db_table': 'labour_operation_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoDetails',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_no', models.CharField(max_length=45)),
                ('ro_invoice_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ro_service_type', models.CharField(default='Paid', max_length=20)),
                ('ro_mileage', models.FloatField(blank=True, null=True)),
                ('ro_created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('ro_received_date', models.DateField()),
                ('ro_received_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('ro_open_date', models.DateField()),
                ('ro_open_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('ro_promise_date', models.DateField()),
                ('ro_promise_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('ro_closed_date', models.DateField()),
                ('ro_closed_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('ro_closed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('ro_remarks', models.TextField()),
            ],
            options={
                'db_table': 'ro_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoPartDetails',
            fields=[
                ('ro_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_part_qty', models.IntegerField()),
                ('ropart_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.ProductMaster')),
                ('ropart_rodetails', models.ManyToManyField(to='servicesapp.RoDetails')),
            ],
            options={
                'db_table': 'ro_part_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoStatus',
            fields=[
                ('ro_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_status_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ro_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoWorktype',
            fields=[
                ('ro_work_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_work_type_name', models.CharField(max_length=45)),
                ('rowork_lab', models.ManyToManyField(to='servicesapp.LabourDetails')),
            ],
            options={
                'db_table': 'ro_worktype',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rodetails',
            name='rodetails_rostatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicesapp.RoStatus'),
        ),
        migrations.AddField(
            model_name='rodetails',
            name='rodetails_vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.VehicleDetails'),
        ),
        migrations.AddField(
            model_name='rodetails',
            name='rodetails_worktype',
            field=models.ManyToManyField(to='servicesapp.RoWorktype'),
        ),
    ]
