# Generated by Django 2.1 on 2019-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='prod_sold_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
