# Generated by Django 2.1 on 2019-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RcHistory',
            fields=[
                ('rc_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_invoice_no', models.CharField(max_length=30)),
                ('veh_reg_no', models.CharField(max_length=15)),
                ('veh_name', models.CharField(max_length=20)),
                ('veh_model', models.CharField(max_length=15)),
                ('veh_km', models.PositiveIntegerField()),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_mob', models.CharField(max_length=15)),
                ('cust_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cust_addr', models.TextField()),
                ('veh_received_date', models.DateField()),
                ('ro_open_date', models.DateField()),
                ('ro_closed_date', models.DateField()),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_qty', models.PositiveIntegerField()),
                ('ro_lab', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rc_history',
                'managed': True,
            },
        ),
    ]
